site:
  name:
    class: text
    custom: Solitude
  siteIcon: /img/favicon.png
  icon: https://7.isyangs.cn/34/65ed3a36ab0e5-34.jpg

nav:
  group:
    é¡¹ç›®:
      Solitude: https://github.com/valor-x/hexo-theme-solitude || https://7.isyangs.cn/34/65ed3a36ab0e5-34.jpg

  menu:
    æ–‡åº“:
      æ–‡ç« åˆ—è¡¨: /archives/ || sco-folder-fill
      å…¨éƒ¨åˆ†ç±»: /categories/ || sco-checkbox-multiple-blank-fill
      å…¨éƒ¨æ ‡ç­¾: /tags/ || sco-price-tag-fill
    å¨±ä¹:
      éŸ³ä¹: /songs/ || sco-disc-fill
      è¯»ä¹¦: /books/ || sco-book-mark-fill
      ç”µå½±: /movies/ || sco-film-fill
    æˆ‘çš„:
      å³åˆ»çŸ­æ–‡: /essay/ || sco-says
      åœ¨çº¿å·¥å…·: /tlink/ || sco-tools-fill
      æˆ‘çš„è£…å¤‡: /equipment/ || sco-laptop-line
    å…³äº:
      å…³äºæˆ‘: /about/ || sco-contacts-fill
      éŸ³ä¹é¦†: /music/ || sco-disc-fill
    ç¤ºä¾‹: /links/
    ç•™è¨€æ¿: /messageboard/

  right:
    random: true
    console: true
    custom:
      - name: Open On Github
        url: https://github.com/valor-x/hexo-theme-solitude
        icon: sco-github-line
        onclick:
        id: travellings_button

hometop:
  banner:
    enable: true
    title: ä¸€æ¬¾ä¼˜é›…<br>çš„Hexo ä¸»é¢˜
    url: Hexo Theme Solitude
    icon:
      HTML:
        img: https://7.isyangs.cn/34/65ed41bb25d03-34.png
        color: "#e9572b"
      JS:
        img: https://7.isyangs.cn/34/65ed41c9ca3f7-34.png
        color: "#f7cb4f"
      Kotlin:
        img: https://7.isyangs.cn/34/65ed41e858ca4-34.png
        color: "#ffffff"
      Docker:
        img: https://7.isyangs.cn/34/65ed41f609691-34.png
        color: "#57b6e6"
      Flutter:
        img: https://7.isyangs.cn/34/65ed4201c2532-34.png
        color: "#ffffff"
      WebPack:
        img: https://7.isyangs.cn/34/65ed420f30a30-34.png
        color: "#2e3a41"
      Git:
        img: https://7.isyangs.cn/34/65ed421e5a102-34.png
        color: "#df5b40"

  group:
    ä½œè€…: https://github.com/efuo || sco-github-line || linear-gradient(to right,#358bff,#15c6ff)
    æ–‡æ¡£: https://solitude-docs.efu.me || sco-book-mark-fill || linear-gradient(to right,#f7cb4f,#e9572b)

  recommendList:
    sup: ç½®é¡¶
    title: å‰å¾€æ–‡æ¡£
    url: https://solitude-docs.efu.me
    img: /img/default.png
    color: "none"

aside:
  home:
    noSticky: "about,flip"
    Sticky: "allInfo"
  post:
    noSticky: "about,flip"
    Sticky: "newestPost"
  page:
    noSticky: "about,flip"
    Sticky: "newestPost,allInfo"
  card:
    author:
      img: https://7.isyangs.cn/34/65ed3a36ab0e5-34.jpg
      sticker: https://7.isyangs.cn/34/65ed3a8bdf1ae-34.png
    url: https://efu.me/
    content: åˆ†äº«è‡ªå·±å¯¹ç¼–ç¨‹çš„<b>çƒ­çˆ±</b>ï¼Œå¯¹ç¾å¥½ç”Ÿæ´»çš„<b>å‘å¾€</b>ï¼Œå¯¹çŸ¥è¯†æµ·æ´‹<b>æ¢ç´¢å†ç¨‹</b>ã€‚
    content2: ç›¸ä¿¡ä½ å¯ä»¥åœ¨è¿™é‡Œæ‰¾åˆ°å¯¹ä½ æœ‰ç”¨çš„çŸ¥è¯†å’Œæ•™ç¨‹ã€‚
    sayhello:
      morning: ä¸€æ—¥ä¹‹è®¡åœ¨äºæ™¨
      noon: åƒé¥±äº†æ‰æœ‰åŠ›æ°”å¹²æ´»
      afternoon: é›†ä¸­ç²¾åŠ›ï¼Œæ”»å…‹éš¾å…³
      night: ä¸è¦å¤ªåŠ³ç´¯äº†ï¼Œæ—©ç¡æ›´å¥åº·
      goodnight: ç¡ä¸ªå¥½è§‰ï¼Œä¿è¯ç²¾åŠ›å……æ²›
    sayhello2:
      - ğŸ¤–ï¸ æ•°ç ç§‘æŠ€çˆ±å¥½è€…
      - ğŸ” åˆ†äº«ä¸çƒ­å¿ƒå¸®åŠ©
      - ğŸ  æ™ºèƒ½å®¶å±…å°èƒ½æ‰‹
      - ğŸ”¨ è®¾è®¡å¼€å‘ä¸€æ¡é¾™
      - ğŸ¤ ä¸“ä¿®äº¤äº’ä¸è®¾è®¡
      - ğŸƒ è„šè¸å®åœ°è¡ŒåŠ¨æ´¾
      - ğŸ§± å›¢é˜Ÿå°ç»„å‘åŠ¨æœº
      - ğŸ’¢ å£®æ±‰äººç‹ è¯ä¸å¤š
      - ğŸ® ç”µç«æ¸¸æˆçˆ±å¥½è€…
    information:
      Github: https://github.com/valor-x/hexo-theme-solitude || sco-github-line
      Telegram: https://t.me/efuome || sco-telegram-line

  flip:
    favicon: "https://7.isyangs.cn/34/65ed42f5598a8-34.png"
    face: "https://7.isyangs.cn/34/65ed430337020-34.png"
    backface: "https://7.isyangs.cn/34/65ed431894af3-34.png"
    backcolor: "var(--sco-blue)"

  toc:
    post: true
    page: false
    vague: true

  tags:
    enable: false
    limit: 20
    highlight: false
    list:
      - "Solitude-ä½¿ç”¨"

  archive:
    enable: false
    type: "month"

  siteinfo:
    postcount: true
    wordcount: true
    pv: true
    uv: true
    updatetime: true
    runtimeenable: true
    runtime: "2023-04-20 00:00:00"

page:
  error: true
  tags: true
  categories: true
  default:
    cover:
      - /img/default.png

post:
  default:
    cover:
      - https://api.qjqq.cn/api/Img
    locate: è¡¡é˜³
    copyright:
      enable: true
      license: CC BY-NC-SA 4.0
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
      author:
        enable: false
        author_back: /img/pwa/180.png
  meta:
    date: true
    updated: true
    locate: true
    wordcount: true
    readtime: true
    pv: true
    comment: false
  award:
    enable: true
    wechat: https://7.isyangs.cn/34/65ed433fef9e9-34.png
    alipay: https://7.isyangs.cn/34/65ed434e0b8d7-34.png
    url: https://efu.me/
  rss: /atom.xml
  covercolor:
    enable: true
    mode: api
    api: https://api.qjqq.cn/api/Imgcolor?img=
    time: 43200000

theme_color:
  dark: "#ffc848"
  dark_op: "#f2b94b23"
  dark_op_deep: "#f2b94bdd"
  dark_none: "#f2b94b00"
  light: "#425AEF"
  light_op: "#4259ef23"
  light_op_deep: "#4259efdd"
  light_none: "#4259ef01"

display_mode:
  type: auto
  universe: true

related_post:
  enable: true
  limit: 2
  date_type: created

footer:
  information:
    left:
      Github: https://github.com/efuo || sco-github-line
      Mail: mailto:o@efu.me || sco-mail-line
    right:
      Bilibili: https://space.bilibili.com/1329819902 || sco-bilibili-line
      æŠ–éŸ³: https://v.douyin.com/iJsLc8jt/ || sco-douyin-fill

  group:
    å¯¼èˆª:
      å½’æ¡£: /archives/
      åˆ†ç±»: /categories/
      æ ‡ç­¾: /tags/
    æœåŠ¡:
      51laç»Ÿè®¡: https://v6.51.la/
    æ”¯æŒ:
      çˆ±å‘ç”µ: https://afdian.net/a/efu0u0
  randomlink: true
  privacy: https://efu.me/
  license: https://efu.me/
  links:
    - name: ä¸»é¢˜
      url: https://github.com/valor-x/hexo-theme-solitude
    - name: ä½œè€…åšå®¢
      url: https://efu.me/
    - name: è®¢é˜…
      url: /atom.xml

errorpage:
  img: /img/6401a7906aa4a.gif
  text: =awa= é¡µé¢èµ°ä¸¢äº†
  recommendList: true

says:
  enable: true
  home_mini: false
  style: 2
  strip: 30

meting_api: "https://meting.qjqq.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r"
music:
  enable: true
  id: 8407304077
  server: netease
  type: playlist
  volume: 0.8
  mutex: true

capsule:
  enable: true
  id: 8407304077
  server: netease
  type: playlist

album:
  enable: false
  limit: 6

keyboard:
  enable: true
  list:
    - name: å…³é—­å¿«æ·é”®åŠŸèƒ½
      key: K
      func: keyboard
    - name: æ‰“å¼€ä¸­æ§å°
      key: A
      sco: showConsole
    - name: æ’­æ”¾/æš‚åœéŸ³ä¹
      key: M
      sco: musicToggle
    - name: æ‰“å¼€å‹æƒ…é“¾æ¥
      key: L
      url: "/links/"

lazyload:
  enable: true
  placeholder: /img/loading.gif
  errorimg: /img/error_load.png

loading:
  fullpage: true
  pace: true

hightlight:
  enable: true
  hightlimit: 200
  copy: true
  expand: true
  theme: default
  color: vscode

lightbox: true
fancybox: true
mediumZoom: false

translate:
  enable: true
  defaultEncoding: 2
  translateDelay: 0

opengraph:
  enable: true
  options:
    twitter_card: summary_large_image
    twitter_image: /img/favicon.png
    twitter_id: Efuo
    twitter_site: Solitude

wordcount: true
busuanzi: true

search:
  enable: true
  type: local
  local:
    preload: false
    CDN:

rightside:
  enable: true

post_ai:
  enable: true
  modelName: GPT 4
  key: Qi7QIXLOrxLCyKBW0bie
  talk: æˆ‘æ˜¯ Efuo å¼€å‘çš„æ‘˜è¦ç”ŸæˆåŠ©ç†ScoGPTï¼ŒScoGPTåœ¨é™æ€éƒ¨ç½²æ—¶è¿›è¡Œæ‘˜è¦çš„æ’°å†™ï¼Œå¹¶ä¸”åœ¨è®¿å®¢è®¿é—®æ—¶é€šè¿‡ScoCorrectionè½¬è¯‘åçš„æ–‡æœ¬æ‘˜è¦å®ç°å·¥å…·ã€‚æˆ‘åœ¨è¿™é‡Œåªè´Ÿè´£å·²ç»ç”Ÿæˆçš„æ‘˜è¦æ˜¾ç¤ºï¼Œä½ æ— æ³•ä¸æˆ‘ç›´æ¥æ²Ÿé€šï¼Œä½†æˆ‘å¯ä»¥å›ç­”ä¸€äº›é¢„è®¾çš„é—®é¢˜ã€‚
  randomPost: true
  report: https://efu.me/
  tips: æ­¤å†…å®¹æ ¹æ®æ–‡ç« ç”Ÿæˆï¼Œå¹¶ç»è¿‡äººå·¥å®¡æ ¸ï¼Œä»…ç”¨äºæ–‡ç« å†…å®¹çš„è§£é‡Šä¸æ€»ç»“

katex:
  enable: false
  per_page: false 
  copytex: false 

moments:
  angle: false

comment:
  enable: true
  type: twikoo 
  commentBarrage: true 
  newComment: true 
  randomInfoStart:
    - "èªæ•çš„"
    - "å¯çˆ±çš„"
    - "ç¾ä¸½çš„"
  randomInfoEnd:
    - "ç™½èœ"
    - "å°å¯çˆ±"
    - "å°ä»™å¥³"
  twikoo:  # https://twikoo.js.org/
    envId: https://twikooo.netlify.app/.netlify/functions/twikoo # url: https://twikoo.sondy.top/
    lang: "zh-CN" # è¯­è¨€
    accessToken: # accessToken



verify_site:
#  - name: google-site-verification
#    content: xxxxxx
#  - name: baidu-site-verification
#    content: xxxxxxx

css_prefix: true

extends:
  head: 
  body: 

pwa:
  enable: true
  manifest: /manifest.json 
  theme_color: "#ffffff" 
  mask_icon: /img/pwa/180.png 
  apple_touch_icon: /img/pwa/180.png 
  bookmark_icon: /img/pwa/180.png 
  favicon_32_32: /img/pwa/32.png 
  favicon_16_16: /img/pwa/16.png 

CDN:
  internal: cdnjs
  third_party: cdnjs
  version: true
  custom_format: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  option:
    scoicon_css: https://cdn2.codesign.qq.com/icons/7pOrz0WXB5ZWJPX/latest/iconfont.css
    waterfall: /js/waterfall.min.js
    universe_js: /js/universe.min.js